kind: PersistentVolume
apiVersion: v1
metadata:
  name: mysql-init-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 50Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/opt/volume/init_sql"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-init-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi
